-- ============================================================
-- Seed Data — Top NSE Stocks (Nifty 50 components)
-- ============================================================

INSERT INTO stocks (symbol, name, exchange, sector, industry) VALUES
    ('RELIANCE',  'Reliance Industries Limited',       'NSE', 'Energy',            'Oil & Gas'),
    ('TCS',       'Tata Consultancy Services',         'NSE', 'Technology',         'IT Services'),
    ('HDFCBANK',  'HDFC Bank Limited',                 'NSE', 'Financial Services', 'Banking'),
    ('INFY',      'Infosys Limited',                   'NSE', 'Technology',         'IT Services'),
    ('ICICIBANK', 'ICICI Bank Limited',                'NSE', 'Financial Services', 'Banking'),
    ('HINDUNILVR','Hindustan Unilever Limited',        'NSE', 'FMCG',              'Consumer Goods'),
    ('ITC',       'ITC Limited',                      'NSE', 'FMCG',              'Conglomerate'),
    ('SBIN',      'State Bank of India',               'NSE', 'Financial Services', 'Banking'),
    ('BHARTIARTL','Bharti Airtel Limited',             'NSE', 'Telecom',           'Telecommunications'),
    ('KOTAKBANK', 'Kotak Mahindra Bank Limited',       'NSE', 'Financial Services', 'Banking'),
    ('LT',        'Larsen & Toubro Limited',           'NSE', 'Industrials',       'Construction'),
    ('HCLTECH',   'HCL Technologies Limited',          'NSE', 'Technology',         'IT Services'),
    ('ASIANPAINT','Asian Paints Limited',              'NSE', 'Materials',         'Paints'),
    ('AXISBANK',  'Axis Bank Limited',                 'NSE', 'Financial Services', 'Banking'),
    ('WIPRO',     'Wipro Limited',                     'NSE', 'Technology',         'IT Services'),
    ('MARUTI',    'Maruti Suzuki India Limited',       'NSE', 'Automobiles',       'Auto'),
    ('SUNPHARMA', 'Sun Pharmaceutical Industries',    'NSE', 'Healthcare',         'Pharmaceuticals'),
    ('ULTRACEMCO','UltraTech Cement Limited',         'NSE', 'Materials',         'Cement'),
    ('TITAN',     'Titan Company Limited',             'NSE', 'Consumer Goods',    'Jewellery'),
    ('BAJFINANCE','Bajaj Finance Limited',             'NSE', 'Financial Services', 'NBFC'),
    ('NTPC',      'NTPC Limited',                     'NSE', 'Utilities',          'Power'),
    ('POWERGRID', 'Power Grid Corporation of India',  'NSE', 'Utilities',          'Power'),
    ('ONGC',      'Oil and Natural Gas Corporation',  'NSE', 'Energy',             'Oil & Gas'),
    ('TATAMOTORS','Tata Motors Limited',              'NSE', 'Automobiles',       'Auto'),
    ('M&M',       'Mahindra & Mahindra Limited',      'NSE', 'Automobiles',       'Auto'),
    ('COALINDIA', 'Coal India Limited',               'NSE', 'Energy',             'Mining'),
    ('GRASIM',    'Grasim Industries Limited',        'NSE', 'Materials',          'Diversified'),
    ('ADANIENT',  'Adani Enterprises Limited',        'NSE', 'Industrials',        'Conglomerate'),
    ('TECHM',     'Tech Mahindra Limited',            'NSE', 'Technology',          'IT Services'),
    ('DRREDDY',   'Dr. Reddy Laboratories',           'NSE', 'Healthcare',          'Pharmaceuticals'),
    ('CIPLA',     'Cipla Limited',                    'NSE', 'Healthcare',          'Pharmaceuticals'),
    ('EICHERMOT', 'Eicher Motors Limited',            'NSE', 'Automobiles',        'Auto'),
    ('HEROMOTOCO','Hero MotoCorp Limited',            'NSE', 'Automobiles',        'Auto'),
    ('BAJAJFINSV','Bajaj Finserv Limited',            'NSE', 'Financial Services',  'NBFC'),
    ('INDUSINDBK','IndusInd Bank Limited',            'NSE', 'Financial Services',  'Banking'),
    ('JSWSTEEL',  'JSW Steel Limited',                'NSE', 'Materials',           'Steel'),
    ('TATASTEEL', 'Tata Steel Limited',               'NSE', 'Materials',           'Steel'),
    ('HINDALCO',  'Hindalco Industries Limited',      'NSE', 'Materials',           'Aluminium'),
    ('NESTLEIND', 'Nestle India Limited',             'NSE', 'FMCG',               'Food'),
    ('DIVISLAB',  'Divi''s Laboratories Limited',    'NSE', 'Healthcare',          'Pharmaceuticals'),
    ('BRITANNIA', 'Britannia Industries Limited',     'NSE', 'FMCG',               'Food'),
    ('BPCL',      'Bharat Petroleum Corporation',     'NSE', 'Energy',              'Oil & Gas'),
    ('HDFCLIFE',  'HDFC Life Insurance Company',     'NSE', 'Financial Services',  'Insurance'),
    ('SBILIFE',   'SBI Life Insurance Company',      'NSE', 'Financial Services',  'Insurance'),
    ('APOLLOHOSP','Apollo Hospitals Enterprise',     'NSE', 'Healthcare',          'Hospitals'),
    ('TATACONSUM','Tata Consumer Products Limited',  'NSE', 'FMCG',               'Consumer Goods'),
    ('ADANIPORTS','Adani Ports & SEZ Limited',       'NSE', 'Industrials',         'Infrastructure'),
    ('UPL',       'UPL Limited',                     'NSE', 'Materials',           'Agrochemicals'),
    ('WIPRO',     'Wipro Limited',                   'NSE', 'Technology',           'IT Services')
ON CONFLICT (symbol) DO NOTHING;
