package com.marketai.dataplatform.domain;

public enum IssueType {
    HOLDING_MISMATCH, MISSING_TRANSACTION, POSSIBLE_DUPLICATE, DUPLICATE_TRANSACTION, CONFLICTING_SOURCES,
    UNCONFIRMED_TRANSACTION, CASH_MISMATCH, VALUATION_MISMATCH
}
