package com.marketai.dataplatform.domain;

public enum SuspectedCause {
    MISSING_TRANSACTION, DUPLICATE_TRANSACTION, SWITCH, DIVIDEND_REINVESTMENT, CORPORATE_ACTION,
    DATA_DELAY, MANUAL_ADJUSTMENT, SOURCE_ERROR
}
